# Lab 1 : Introduction to NumPy

---



# Importing the libraries

In [1]:
import numpy as np
import math
import time

In [2]:
print("Hello World")

Hello World


In [3]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [4]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.3248725  0.48559675]
 [0.76202914 0.84061453]]


In [5]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[2 3]
 [6 7]]
2
77


In [6]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [7]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [8]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [9]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a NumPy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [10]:
x = np.array([1, 2])   # Let NumPy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let NumPy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


In [11]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [12]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [14]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [15]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [16]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [17]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [18]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). NumPy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


# 6. Reshaping arrays with NumPy

In [19]:
def reshape_array(arr):
  return arr.reshape(arr.shape[0]*arr.shape[1]*arr.shape[2], 1)

In [20]:
arr = np.random.rand(1, 2, 3)
reshaped_array = reshape_array(arr)
print("Reshaped Array's Shape: ")
print(reshaped_array.shape)

Reshaped Array's Shape: 
(6, 1)


# 7. Building a basic mathematical function with NumPy

## Using math.exp

In [21]:
def sigmoid_math(x):
  return ( 1 / (1 + math.exp(-x)) )

In [22]:
print("Sigmoid Function using math.exp: ")
print(sigmoid_math(4))

Sigmoid Function using math.exp: 
0.9820137900379085


In [23]:
x_val = np.array([1, 2, 3, 4, 5])
sigmoid_val = sigmoid_math(x_val)

TypeError: only size-1 arrays can be converted to Python scalars

## Using numpy.exp

In [24]:
def sigmoid_numpy(x):
    return ( 1 / (1 + np.exp(-x)) )

In [25]:
x_val = np.array([1, 2, 3, 4, 5])
sigmoid_val = sigmoid_numpy(x_val)
print("Sigmoid Function using numpy.exp:")
print(sigmoid_val)

Sigmoid Function using numpy.exp:
[0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]


# 8. Implementing a function on a matrix

In [26]:
def softmax(mtx):
    exp_mtx = np.exp(mtx)
    return exp_mtx / np.sum(exp_mtx, axis=1, keepdims=True)

In [27]:
mtx = np.array([[1.2, 2.4, 3.6], [3.6, 2.4, 1.2]])
result = softmax(mtx)
print("Softmax Function Results: ")
print(result)

Softmax Function Results: 
[[0.06517506 0.21638881 0.71843614]
 [0.71843614 0.21638881 0.06517506]]


# 9. Finding dot product using NumPy

## Using standard python

In [28]:
def dot_product_python(array1, array2):
    return sum(x * y for x, y in zip(array1, array2))

## Using numpy.dot function

In [29]:
def dot_product_numpy(array1, array2):
    return np.dot(array1, array2)

## Time difference

In [31]:
arr1 = list(range(1000))
arr2 = list(range(1000))
start_time = time.time()
result_using_simple_python = dot_product_python(arr1, arr2)
elapsed_time_simple_python = time.time() - start_time

print("Simple Python implementation result:", result_using_simple_python)
print("Time taken (Python):", elapsed_time_simple_python)

arr3 = np.array(arr1)
arr4 = np.array(arr2)
start_time = time.time()
result_using_numpy = dot_product_numpy(arr3, arr4)
elapsed_time_numpy = time.time() - start_time

print("Numpy implementation result:", result_using_numpy)
print("Time taken (NumPy):", elapsed_time_numpy)

Simple Python implementation result: 332833500
Time taken (Python): 0.0003325939178466797
Numpy implementation result: 332833500
Time taken (NumPy): 0.00015401840209960938


# 10. Finding outer product using NumPy

## Using standard python

In [32]:
def outer_product_python(array1, array2):
    return [[a * b for b in array2] for a in array1]

## Using numpy.outer function

In [33]:
def outer_product_numpy(arr1, arr2):
    return np.outer(arr1, arr2)

## Time difference

In [34]:
start_time = time.time()
result_using_simple_python = outer_product_python(arr1, arr2)
elapsed_time_simple_python = time.time() - start_time

print("Python implementation result: ")
for row in result_using_simple_python[:4]:
    print(row[:4])
print("Time taken (Python): ", elapsed_time_simple_python)

start_time = time.time()
result_using_numpy = outer_product_numpy(arr3, arr4)
elapsed_time_using_numpy = time.time() - start_time


print("NumPy implementation result: ")
print(result_using_numpy[:4, :4])
print("Time taken (NumPy): ", elapsed_time_using_numpy)

Python implementation result: 
[0, 0, 0, 0]
[0, 1, 2, 3]
[0, 2, 4, 6]
[0, 3, 6, 9]
Time taken (Python):  0.08939647674560547
NumPy implementation result: 
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
Time taken (NumPy):  0.004548788070678711


# 11. Defining loss function

## Using standard python lists

In [35]:
def loss_f1_python(list1, list2):
    return sum(abs(a - b) for a, b in zip(list1, list2))

In [36]:
def loss_f2_python(list1, list2):
    return sum((a - b) ** 2 for a, b in zip(list1, list2))

## Using numpy arrays

In [37]:
def loss_f1_numpy(arr1, arr2):
    return np.sum(np.abs(arr1 - arr2))

In [38]:
def loss_f2_numpy(arr1, arr2):
    return np.sum((arr1 - arr2) ** 2)

## Time difference

In [39]:
vector1 = np.array(list(range(1000)))
vector2 = np.array(list(range(5,1005)))

start_time = time.time()
loss_f1_result_python = loss_f1_python(vector1, vector2)
elapsed_time_loss1_f1_python = time.time() - start_time

start_time = time.time()
loss_f1_result_numpy = loss_f1_numpy(vector1, vector2)
elapsed_time_loss1_f1_numpy = time.time() - start_time

start_time = time.time()
loss_f2_result_python = loss_f2_python(vector1, vector2)
elapsed_time_loss2_f2_python = time.time() - start_time

start_time = time.time()
loss_f2_result_numpy = loss_f2_numpy(vector1, vector2)
elapsed_time_loss2_f2_numpy = time.time() - start_time

print("Loss Funtion 1:")
print("Python implementation result: ", loss_f1_result_python)
print("Python implementation time: ", elapsed_time_loss1_f1_python)
print("NumPy implementation result: ", loss_f1_result_numpy)
print("NumPy implementation time: ", elapsed_time_loss1_f1_numpy)

print("Loss Function 2:")
print("Python implementation result: ", loss_f2_result_python)
print("Python implementation time: ", elapsed_time_loss2_f2_python)
print("NumPy implementation result: ", loss_f2_result_numpy)
print("NumPy implementation time: ", elapsed_time_loss2_f2_numpy)

Loss Funtion 1:
Python implementation result:  5000
Python implementation time:  0.00041556358337402344
NumPy implementation result:  5000
NumPy implementation time:  0.00093841552734375
Loss Function 2:
Python implementation result:  25000
Python implementation time:  0.0003795623779296875
NumPy implementation result:  25000
NumPy implementation time:  0.00010418891906738281


# 12. Perform matrix and matrix addition

## Using standard python

In [40]:
def matrix_addition_python(mtx1, mtx2):
    return [[a + b for a, b in zip(row1, row2)] for row1, row2 in zip(mtx1, mtx2)]

## Using numpy

In [41]:
def matrix_addition_numpy(mtx1, mtx2):
    return np.add(mtx1, mtx2)

## Time difference

In [42]:
matrix1 = np.random.rand(20, 30)
matrix2 = np.random.rand(20, 30)

start_time = time.time()
matrix_addition_result_python = matrix_addition_python(matrix1, matrix2)
elapsed_time_python = time.time() - start_time

print("Python implementation result: ")
for row in matrix_addition_result_python[:4]:
    print(row[:4])
print("Python implementation time: ")
print(elapsed_time_python)

start_time = time.time()
matrix_addition_result_numpy = matrix_addition_numpy(matrix1, matrix2)
elapsed_time_numpy = time.time() - start_time

print("NumPy implementation result: ")
print(matrix_addition_result_numpy[:4,:4])
print("NumPy implementation time: ")
print(elapsed_time_numpy)

Python implementation result: 
[0.6671588046063148, 1.7806112507758503, 1.2675193632081276, 1.2705022361548801]
[0.9601096114737218, 1.0701246290516013, 0.537119124092107, 0.5441327132166295]
[1.397384169785051, 1.6279903947351588, 1.1997296287849797, 0.9531933200445901]
[0.6847107851681993, 0.6844282204688842, 1.0570474446661873, 0.30410677697374844]
Python implementation time: 
0.0005085468292236328
NumPy implementation result: 
[[0.6671588  1.78061125 1.26751936 1.27050224]
 [0.96010961 1.07012463 0.53711912 0.54413271]
 [1.39738417 1.62799039 1.19972963 0.95319332]
 [0.68471079 0.68442822 1.05704744 0.30410678]]
NumPy implementation time: 
0.00015115737915039062


# 13. Perform matrix and vector multiplication

## Using standard python

In [43]:
def matrix_vector_multiplication_python(mtx, vec):
    return [sum(a * b for a, b in zip(row, vec)) for row in mtx]

## Using numpy

In [44]:
def matrix_vector_multiplication_numpy(mtx, vec):
    return np.dot(mtx, vec)

## Time difference

In [47]:
matrix = np.random.rand(20, 30)
vector = np.random.rand(30)

start_time = time.time()
matrix_vector_multiplication_result_python = matrix_vector_multiplication_python(matrix, vector)
elapsed_time_python = time.time() - start_time

print("Python implementation result: ", matrix_vector_multiplication_result_python)
print("Python implementation time: ", elapsed_time_python)

start_time = time.time()
matrix_vector_multiplication_result_numpy = matrix_vector_multiplication_numpy(matrix, vector)
elapsed_time_numpy = time.time() - start_time

print("NumPy implementation result: ", matrix_vector_multiplication_result_numpy)
print("NumPy implementation time: ", elapsed_time_numpy)


Python implementation result:  [6.820944222404255, 7.839410226786756, 6.590993081890601, 9.587432025374918, 8.240537976920685, 8.068086366909998, 6.975933683743836, 6.703805539371213, 7.448038907167469, 7.728332333329893, 9.878866918626624, 8.599875975566345, 7.4943862064009386, 9.38629482170005, 6.152242268246153, 6.422606472535745, 7.457538777881319, 6.480746663382905, 7.111008308884692, 7.35802826343736]
Python implementation time:  0.0003235340118408203
NumPy implementation result:  [6.82094422 7.83941023 6.59099308 9.58743203 8.24053798 8.06808637
 6.97593368 6.70380554 7.44803891 7.72833233 9.87886692 8.59987598
 7.49438621 9.38629482 6.15224227 6.42260647 7.45753878 6.48074666
 7.11100831 7.35802826]
NumPy implementation time:  0.00012230873107910156


# 14. Perform matrix and matrix multiplication

## Using standard python

In [48]:
def matrix_matrix_multiplication_python(mtx1, mtx2):
    result = []
    for i in range(len(mtx1)):
        row = []
        for j in range(len(mtx2[0])):
            row.append(sum(mtx1[i][k] * mtx2[k][j] for k in range(len(mtx2))))
        result.append(row)
    return result

## Using numpy

In [49]:
def matrix_matrix_multiplication_numpy(mtx1, mtx2):
    return np.dot(mtx1, mtx2)

## Time difference

In [51]:
matrix3 = np.random.rand(20, 30)
matrix4 = np.random.rand(30, 40)

start_time = time.time()
matrix_matrix_multiplication_result_python = matrix_matrix_multiplication_python(matrix3, matrix4)
elapsed_time_python = time.time() - start_time

print("Python implementation result: ")
for row in matrix_matrix_multiplication_result_python[:5]:
    print(row[:5])
print("Python implementation time: ", elapsed_time_python)

start_time = time.time()
matrix_matrix_multiplication_result_numpy = matrix_matrix_multiplication_numpy(matrix3, matrix4)
elapsed_time_numpy = time.time() - start_time


print("NumPy implementation result: ")
print(matrix_matrix_multiplication_result_numpy[:5,:5])
print("NumPy implementation time: ", elapsed_time_numpy)

Python implementation result: 
[7.683898640107309, 8.10611705364215, 8.685128301554824, 8.119560522015671, 8.215505031128039]
[6.458565074927653, 7.406480423015032, 6.913791791163468, 6.1653227130121655, 7.177986639926521]
[8.341412780916272, 8.196958629760479, 7.733215722024792, 7.8203075403594084, 8.20044606216091]
[7.692706597465791, 7.16125465124356, 7.888439180980285, 7.106347860761761, 7.485100567981029]
[7.772148940600831, 7.818112238856061, 7.790858185387903, 7.281094317311199, 8.450697558149992]
Python implementation time:  0.02089548110961914
NumPy implementation result: 
[[7.68389864 8.10611705 8.6851283  8.11956052 8.21550503]
 [6.45856507 7.40648042 6.91379179 6.16532271 7.17798664]
 [8.34141278 8.19695863 7.73321572 7.82030754 8.20044606]
 [7.6927066  7.16125465 7.88843918 7.10634786 7.48510057]
 [7.77214894 7.81811224 7.79085819 7.28109432 8.45069756]]
NumPy implementation time:  0.005037784576416016
